# -*- coding: utf-8 -*-
"""
/***************************************************************************
 validate
                                 A QGIS plugin
 Herramienta que analiza la estructura de la direccion
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-24
        copyright            : (C) 2023 by Servinformacion
        email                : leonardo.martinez@servinformacion.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load validate class from file validate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .validaciones import validate
    return validate(iface)
