# -*- coding: utf-8 -*-
"""
/***************************************************************************
 validateDialog
                                 A QGIS plugin
 Herramienta que analiza la estructura de la direccion
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-12
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Servinformacion
        email                : leonardo.maetinez@servinformacion.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from .permisos import concederPermisos, obtenerUsuariosYPermisos, revocarPermisosUsuarios, obtenerPermisosDetallados

import os
import psycopg2
import time

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout, QLabel, QListWidgetItem
from PyQt5.QtCore import Qt

from qgis.core import QgsDataSourceUri, QgsVectorLayer, QgsProject
from qgis.utils import iface

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Validaciones Servinfomacion_dialog_base.ui'))
    
FORM_CLASS_WINDOW, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'credentials.ui'))

class validateDialog(QtWidgets.QDialog, FORM_CLASS, FORM_CLASS_WINDOW):
    def __init__(self, parent=None):
        """Constructor."""
        super(validateDialog, self).__init__(parent)
        self.setupUi(self)
        
        self.PBasignacion.clicked.connect(self.asignarUsuarios)
        self.PBvalidarPermisos.clicked.connect(self.validarPermisos)
        self.PBactualizarPermisos.clicked.connect(self.actualizarPermisos)
        self.PBquitarTodosPermisos.clicked.connect(self.quitarTodosPermisos)
        self.PBvalidarConexion.clicked.connect(self.validarConexion)
        self.listUsuariosPermisos.itemSelectionChanged.connect(self.mostrarPermisosUsuario)
        
        self.usuario_actual = None
        self.usuarios_permisos_dict = {}
        self.permisos_usuario_actual = {}
        
    def mensaje(self, status, mess):
        if status == "Error":
            iface.messageBar().pushMessage(status, mess, level = 2, duration = 5)
        if status == "Ejecutado":
            iface.messageBar().pushMessage(status, mess, level = 3, duration = 5)
    
    def credenciales(self):
        bd = self.LEbd.text()
        host = self.LEhost.text()
        usuario = self.LEusuario.text()
        contrasena = self.QPLEcontrasena.text()
        return bd, host, usuario, contrasena
    
    def validarConexion(self):
        """Valida la conexión a la base de datos"""
        import psycopg2
        
        bd, host, usuario, contrasena = self.credenciales()
        
        # Validar que los campos no estén vacíos
        if not all([bd, host, usuario, contrasena]):
            self.mostrarProceso.setText('❌ Error: Completa todos los campos de conexión')
            self.mensaje('Error', 'Completa todos los campos')
            return
        
        self.mostrarProceso.setText('🔄 Validando conexión...\n')
        QApplication.processEvents()
        
        try:
            conn = psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario, 
                password=contrasena, 
                port='5432'
            )
            
            cursor = conn.cursor()
            cursor.execute("SELECT version();")
            version = cursor.fetchone()[0]
            
            cursor.close()
            conn.close()
            
            # Mostrar resultado exitoso
            resumen = "✅ VALIDACIÓN DE CONEXIÓN EXITOSA\n"
            resumen += "=" * 60 + "\n\n"
            resumen += f"🔗 Host: {host}\n"
            resumen += f"📊 Base de datos: {bd}\n"
            resumen += f"👤 Usuario: {usuario}\n"
            resumen += f"🐘 Versión PostgreSQL: {version.split(',')[0]}\n\n"
            resumen += "=" * 60 + "\n"
            resumen += "✓ La conexión a la base de datos es correcta\n"
            resumen += "✓ Puedes proceder con las operaciones\n"
            
            self.mostrarProceso.setText(resumen)
            self.mensaje('Ejecutado', 'Conexión validada exitosamente')
            
        except psycopg2.OperationalError as e:
            resumen = "❌ ERROR DE CONEXIÓN\n"
            resumen += "=" * 60 + "\n\n"
            resumen += f"🔗 Host: {host}\n"
            resumen += f"📊 Base de datos: {bd}\n"
            resumen += f"👤 Usuario: {usuario}\n\n"
            resumen += "Posibles causas:\n"
            resumen += "• Credenciales incorrectas\n"
            resumen += "• Host o puerto incorrecto\n"
            resumen += "• Base de datos no existe\n"
            resumen += "• Servidor PostgreSQL no está disponible\n\n"
            resumen += f"Detalles del error:\n{str(e)}\n"
            
            self.mostrarProceso.setText(resumen)
            self.mensaje('Error', 'Error de conexión')
            
        except Exception as e:
            resumen = "❌ ERROR INESPERADO\n"
            resumen += "=" * 60 + "\n\n"
            resumen += f"Detalles del error:\n{str(e)}\n"
            
            self.mostrarProceso.setText(resumen)
            self.mensaje('Error', str(e))
    
    def run(self, query):
        self.mostrarProceso.setText('Procesando...')
        QApplication.processEvents()
        bd, host, usuario, contrasena = self.credenciales()
        try:
            conn = psycopg2.connect(host = host, database = bd, user = usuario, password = contrasena, port = '5432')
            cursor = conn.cursor()
            cursor.execute(query)
            conn.commit()
            self.mensaje('Ejecutado','Se ha realizado la validación')
            self.mostrarProceso.setText('Proceso Terminado - Se ha realizado la validación exitosamente...')
            
        except psycopg2.OperationalError:
            self.mensaje('Error','Los datos de conexión son erróneos')
            self.mostrarProceso.setText('Error Conexion - Los datos de conexión son erróneos...')
        
        except Exception as e:
            self.mensaje('Error','No se pudo ejecutar el Query')
            self.mostrarProceso.setText('Error query - No se pudo ejecutar el Query...')
    
    def asignarUsuarios(self):
        """Asigna permisos a los usuarios ingresados"""
        from PyQt5.QtWidgets import QMessageBox, QDialog, QVBoxLayout, QLabel, QHBoxLayout, QPushButton
        from PyQt5.QtCore import Qt
        
        # Obtener usuarios
        usuarios_texto = self.TXEusuarios.toPlainText().strip()
        if not usuarios_texto:
            self.mensaje('Error', 'Ingresa al menos un usuario')
            return
        
        # Parsear usuarios
        usuarios = [u.strip() for u in usuarios_texto.split(',') if u.strip()]
        
        # Obtener permisos seleccionados
        permisos_seleccionados = []
        if self.checkAsignSELECT.isChecked():
            permisos_seleccionados.append('SELECT')
        if self.checkAsignINSERT.isChecked():
            permisos_seleccionados.append('INSERT')
        if self.checkAsignUPDATE.isChecked():
            permisos_seleccionados.append('UPDATE')
        if self.checkAsignDELETE.isChecked():
            permisos_seleccionados.append('DELETE')
        
        if not permisos_seleccionados:
            self.mensaje('Error', 'Selecciona al menos un permiso')
            return
        
        # Crear diálogo personalizado
        usuarios_str = ', '.join(usuarios)
        permisos_str = ', '.join(permisos_seleccionados)
        
        dialogo = QDialog(self)
        dialogo.setWindowTitle('Confirmar Asignación de Permisos')
        dialogo.setMinimumWidth(500)
        dialogo.setStyleSheet("""
            QDialog {
                background-color: #f5f5f5;
            }
            QLabel {
                color: #333;
            }
        """)
        
        layout = QVBoxLayout()
        
        # Título
        titulo = QLabel('✓ Confirmar Asignación de Permisos')
        titulo.setStyleSheet('font-weight: bold; font-size: 14px; color: #2196F3; margin-bottom: 15px;')
        layout.addWidget(titulo)
        
        # Contenido
        contenido = QLabel(
            f"<b>¿Deseas asignar los siguientes permisos?</b><br><br>"
            f"<b>Usuarios:</b> {usuarios_str}<br><br>"
            f"<b>Permisos:</b> {permisos_str}<br><br>"
            f"<i>Esta acción se aplicará a TODAS las tablas de la base de datos.</i>"
        )
        contenido.setStyleSheet('color: #555; line-height: 1.6;')
        layout.addWidget(contenido)
        
        layout.addSpacing(20)
        
        # Botones
        botones_layout = QHBoxLayout()
        botones_layout.addStretch()
        
        btn_si = QPushButton('✓ Sí, Asignar')
        btn_si.setMinimumWidth(120)
        btn_si.setMinimumHeight(40)
        btn_si.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
            QPushButton:pressed {
                background-color: #3d8b40;
            }
        """)
        
        btn_no = QPushButton('✗ Cancelar')
        btn_no.setMinimumWidth(120)
        btn_no.setMinimumHeight(40)
        btn_no.setStyleSheet("""
            QPushButton {
                background-color: #f44336;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #da190b;
            }
            QPushButton:pressed {
                background-color: #ba0000;
            }
        """)
        
        botones_layout.addWidget(btn_si)
        botones_layout.addWidget(btn_no)
        botones_layout.addStretch()
        
        layout.addLayout(botones_layout)
        dialogo.setLayout(layout)
        
        # Conectar botones
        btn_si.clicked.connect(dialogo.accept)
        btn_no.clicked.connect(dialogo.reject)
        
        # Mostrar diálogo
        if dialogo.exec_() != QDialog.Accepted:
            self.mostrarProceso.setText('Operación cancelada por el usuario.')
            return
        
        self.mostrarProceso.setText('Procesando asignación de permisos...\n')
        QApplication.processEvents()
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            resumen = self.asignarPermisosAUsuarios(host, bd, usuario_admin, contrasena, usuarios, permisos_seleccionados)
            self.mostrarProceso.setText(resumen)
            self.mensaje('Ejecutado', 'Permisos asignados exitosamente')
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def asignarPermisosAUsuarios(self, host, bd, usuario_admin, contrasena, usuarios, permisos):
        """Asigna permisos a múltiples usuarios en todas las tablas"""
        import psycopg2
        from .permisos import obtenerTablasBaseDatos
        
        resumen = "RESUMEN DE ASIGNACIÓN DE PERMISOS\n"
        resumen += "=" * 60 + "\n\n"
        
        try:
            # Obtener tablas
            tablas = obtenerTablasBaseDatos(host, bd, usuario_admin, contrasena)
            
            resumen += f"📊 Tablas encontradas: {len(tablas)}\n"
            resumen += f"👥 Usuarios a procesar: {len(usuarios)}\n"
            resumen += f"🔐 Permisos a asignar: {', '.join(permisos)}\n\n"
            
            if len(tablas) == 0:
                resumen += "⚠️ No se encontraron tablas en la base de datos\n"
                return resumen
            
            conn = psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario_admin, 
                password=contrasena, 
                port='5432'
            )
            cursor = conn.cursor()
            
            total_permisos = 0
            errores = 0
            
            for usuario in usuarios:
                resumen += f"\n👤 Procesando usuario: {usuario}\n"
                resumen += "-" * 60 + "\n"
                usuario_permisos = 0
                
                for permiso in permisos:
                    permisos_asignados_permiso = 0
                    
                    for esquema, tabla in tablas:
                        try:
                            grant_query = f'GRANT {permiso} ON TABLE "{esquema}"."{tabla}" TO "{usuario}";'
                            cursor.execute(grant_query)
                            usuario_permisos += 1
                            permisos_asignados_permiso += 1
                            total_permisos += 1
                        except psycopg2.Error as e:
                            errores += 1
                            # Solo mostrar errores críticos
                            if "already" not in str(e).lower():
                                resumen += f"   ⚠️ Error en {esquema}.{tabla} ({permiso})\n"
                        except Exception as e:
                            errores += 1
                    
                    if permisos_asignados_permiso > 0:
                        resumen += f"   ✓ {permiso}: {permisos_asignados_permiso} tablas\n"
                
                resumen += f"   📈 Total para {usuario}: {usuario_permisos} permisos\n"
            
            conn.commit()
            cursor.close()
            conn.close()
            
            resumen += "\n" + "=" * 60 + "\n"
            resumen += f"✅ PROCESO COMPLETADO\n"
            resumen += f"   • Total de permisos asignados: {total_permisos}\n"
            resumen += f"   • Usuarios procesados: {len(usuarios)}\n"
            resumen += f"   • Tablas procesadas: {len(tablas)}\n"
            resumen += f"   • Permisos aplicados: {', '.join(permisos)}\n"
            if errores > 0:
                resumen += f"   • Errores encontrados: {errores}\n"
            
            return resumen
            
        except Exception as e:
            raise Exception(f"Error al asignar permisos: {str(e)}")
    
    def validarPermisos(self):
        """Obtiene y muestra los usuarios con permisos en la BD"""
        self.mostrarProceso.setText('Obteniendo usuarios y permisos...')
        QApplication.processEvents()
        
        bd, host, usuario, contrasena = self.credenciales()
        
        try:
            usuarios_permisos = obtenerUsuariosYPermisos(host, bd, usuario, contrasena)
            
            # Limpiar lista anterior
            self.listUsuariosPermisos.clear()
            self.usuarios_permisos_dict = {}
            
            # Agregar usuarios a la lista con checkboxes
            for user, permisos in usuarios_permisos:
                item = QListWidgetItem(user)
                item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
                item.setCheckState(Qt.Checked)
                item.setData(Qt.UserRole, user)
                self.listUsuariosPermisos.addItem(item)
                self.usuarios_permisos_dict[user] = permisos
            
            self.mostrarProceso.setText(f'Se encontraron {len(usuarios_permisos)} usuarios con permisos.')
            self.mensaje('Ejecutado', f'Se encontraron {len(usuarios_permisos)} usuarios')
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def mostrarPermisosUsuario(self):
        """Muestra los permisos del usuario seleccionado"""
        from PyQt5.QtWidgets import QTableWidgetItem
        
        items_seleccionados = self.listUsuariosPermisos.selectedItems()
        
        if not items_seleccionados:
            self.permisosGroupBox.setTitle("Selecciona un usuario para ver/editar permisos")
            self.checkSELECT.setChecked(False)
            self.checkINSERT.setChecked(False)
            self.checkUPDATE.setChecked(False)
            self.checkDELETE.setChecked(False)
            self.tablasPermisosTable.setRowCount(0)
            return
        
        usuario = items_seleccionados[0].data(Qt.UserRole)
        self.usuario_actual = usuario
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            # Obtener permisos detallados del usuario
            permisos_detallados = obtenerPermisosDetallados(host, bd, usuario_admin, contrasena, usuario)
            
            self.permisos_usuario_actual = permisos_detallados
            
            # Actualizar checkboxes
            self.checkSELECT.setChecked(permisos_detallados.get('SELECT', False))
            self.checkINSERT.setChecked(permisos_detallados.get('INSERT', False))
            self.checkUPDATE.setChecked(permisos_detallados.get('UPDATE', False))
            self.checkDELETE.setChecked(permisos_detallados.get('DELETE', False))
            
            # Llenar tabla con permisos por tabla
            tablas = permisos_detallados.get('tablas', [])
            self.tablasPermisosTable.setRowCount(len(tablas))
            
            for row, tabla_info in enumerate(tablas):
                # Validar que tabla_info tenga suficientes elementos
                if len(tabla_info) < 6:
                    continue
                    
                esquema = tabla_info[0] if tabla_info[0] else ""
                tabla = tabla_info[1] if tabla_info[1] else ""
                tiene_select = tabla_info[2] if tabla_info[2] is not None else False
                tiene_insert = tabla_info[3] if tabla_info[3] is not None else False
                tiene_update = tabla_info[4] if tabla_info[4] is not None else False
                tiene_delete = tabla_info[5] if tabla_info[5] is not None else False
                
                # Esquema
                item_esquema = QTableWidgetItem(str(esquema))
                item_esquema.setFlags(item_esquema.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 0, item_esquema)
                
                # Tabla
                item_tabla = QTableWidgetItem(str(tabla))
                item_tabla.setFlags(item_tabla.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 1, item_tabla)
                
                # SELECT
                item_select = QTableWidgetItem("✓" if tiene_select else "")
                item_select.setFlags(item_select.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 2, item_select)
                
                # INSERT
                item_insert = QTableWidgetItem("✓" if tiene_insert else "")
                item_insert.setFlags(item_insert.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 3, item_insert)
                
                # UPDATE
                item_update = QTableWidgetItem("✓" if tiene_update else "")
                item_update.setFlags(item_update.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 4, item_update)
                
                # DELETE
                item_delete = QTableWidgetItem("✓" if tiene_delete else "")
                item_delete.setFlags(item_delete.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 5, item_delete)
            
            self.permisosGroupBox.setTitle(f"Permisos para: {usuario}")
            
        except Exception as e:
            self.mensaje('Error', f'Error al obtener permisos: {str(e)}')
    
    def actualizarPermisos(self):
        """Actualiza permisos del usuario seleccionado basado en los checkboxes"""
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QLabel, QHBoxLayout, QPushButton
        
        if not self.usuario_actual:
            self.mensaje('Error', 'Selecciona un usuario primero')
            return
        
        # Obtener permisos seleccionados
        permisos_activos = []
        if self.checkSELECT.isChecked():
            permisos_activos.append('SELECT')
        if self.checkINSERT.isChecked():
            permisos_activos.append('INSERT')
        if self.checkUPDATE.isChecked():
            permisos_activos.append('UPDATE')
        if self.checkDELETE.isChecked():
            permisos_activos.append('DELETE')
        
        # Crear diálogo personalizado
        permisos_str = ', '.join(permisos_activos) if permisos_activos else 'NINGUNO'
        
        dialogo = QDialog(self)
        dialogo.setWindowTitle('Confirmar Actualización de Permisos')
        dialogo.setMinimumWidth(500)
        dialogo.setStyleSheet("""
            QDialog {
                background-color: #f5f5f5;
            }
            QLabel {
                color: #333;
            }
        """)
        
        layout = QVBoxLayout()
        
        # Título
        titulo = QLabel('💾 Confirmar Actualización de Permisos')
        titulo.setStyleSheet('font-weight: bold; font-size: 14px; color: #FF9800; margin-bottom: 15px;')
        layout.addWidget(titulo)
        
        # Contenido
        contenido = QLabel(
            f"<b>¿Deseas actualizar los permisos del usuario?</b><br><br>"
            f"<b>Usuario:</b> {self.usuario_actual}<br><br>"
            f"<b>Nuevos Permisos:</b> {permisos_str}<br><br>"
            f"<i>Los permisos no seleccionados serán revocados.</i>"
        )
        contenido.setStyleSheet('color: #555; line-height: 1.6;')
        layout.addWidget(contenido)
        
        layout.addSpacing(20)
        
        # Botones
        botones_layout = QHBoxLayout()
        botones_layout.addStretch()
        
        btn_si = QPushButton('✓ Sí, Actualizar')
        btn_si.setMinimumWidth(120)
        btn_si.setMinimumHeight(40)
        btn_si.setStyleSheet("""
            QPushButton {
                background-color: #FF9800;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #e68900;
            }
            QPushButton:pressed {
                background-color: #cc7700;
            }
        """)
        
        btn_no = QPushButton('✗ Cancelar')
        btn_no.setMinimumWidth(120)
        btn_no.setMinimumHeight(40)
        btn_no.setStyleSheet("""
            QPushButton {
                background-color: #f44336;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #da190b;
            }
            QPushButton:pressed {
                background-color: #ba0000;
            }
        """)
        
        botones_layout.addWidget(btn_si)
        botones_layout.addWidget(btn_no)
        botones_layout.addStretch()
        
        layout.addLayout(botones_layout)
        dialogo.setLayout(layout)
        
        # Conectar botones
        btn_si.clicked.connect(dialogo.accept)
        btn_no.clicked.connect(dialogo.reject)
        
        # Mostrar diálogo
        if dialogo.exec_() != QDialog.Accepted:
            self.mensaje('Ejecutado', 'Operación cancelada')
            return
        
        self.mostrarProceso.setText('Actualizando permisos...')
        QApplication.processEvents()
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            # Obtener todas las tablas del usuario
            tablas = self.permisos_usuario_actual.get('tablas', [])
            
            if not tablas:
                self.mensaje('Error', 'No hay tablas para actualizar')
                return
            
            # Aplicar permisos
            self.aplicarPermisosUsuario(host, bd, usuario_admin, contrasena, self.usuario_actual, permisos_activos, tablas)
            
            self.mostrarProceso.setText(f'Permisos actualizados exitosamente para {self.usuario_actual}.')
            self.mensaje('Ejecutado', f'Permisos actualizados para {self.usuario_actual}')
            
            # Actualizar lista
            self.validarPermisos()
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def aplicarPermisosUsuario(self, host, bd, usuario_admin, contrasena, usuario_objetivo, permisos_activos, tablas):
        """Aplica los permisos seleccionados al usuario"""
        import psycopg2
        
        try:
            conn = psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario_admin, 
                password=contrasena, 
                port='5432'
            )
            cursor = conn.cursor()
            
            # Primero revocar todos los permisos
            for esquema, tabla, _, _, _, _ in tablas:
                try:
                    cursor.execute(f'REVOKE ALL ON TABLE "{esquema}"."{tabla}" FROM "{usuario_objetivo}";')
                except:
                    pass
            
            # Luego otorgar solo los permisos seleccionados
            for permiso in permisos_activos:
                for esquema, tabla, _, _, _, _ in tablas:
                    try:
                        cursor.execute(f'GRANT {permiso} ON TABLE "{esquema}"."{tabla}" TO "{usuario_objetivo}";')
                    except:
                        pass
            
            conn.commit()
            cursor.close()
            conn.close()
            
        except Exception as e:
            raise Exception(f"Error al aplicar permisos: {str(e)}")
    
    def quitarTodosPermisos(self):
        """Quita todos los permisos del usuario seleccionado"""
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QLabel, QHBoxLayout, QPushButton
        
        if not self.usuario_actual:
            self.mensaje('Error', 'Selecciona un usuario primero')
            return
        
        # Crear diálogo personalizado
        dialogo = QDialog(self)
        dialogo.setWindowTitle('Confirmar Eliminación de Permisos')
        dialogo.setMinimumWidth(500)
        dialogo.setStyleSheet("""
            QDialog {
                background-color: #f5f5f5;
            }
            QLabel {
                color: #333;
            }
        """)
        
        layout = QVBoxLayout()
        
        # Título
        titulo = QLabel('🚫 Confirmar Eliminación de Permisos')
        titulo.setStyleSheet('font-weight: bold; font-size: 14px; color: #f44336; margin-bottom: 15px;')
        layout.addWidget(titulo)
        
        # Contenido
        contenido = QLabel(
            f"<b>⚠️ ADVERTENCIA: Esta acción no se puede deshacer</b><br><br>"
            f"¿Estás seguro de que deseas quitar <b>TODOS</b> los permisos al usuario?<br><br>"
            f"<b>Usuario:</b> {self.usuario_actual}<br><br>"
            f"<i>Se quitarán todos los permisos en todas las tablas y esquemas.</i>"
        )
        contenido.setStyleSheet('color: #555; line-height: 1.6;')
        layout.addWidget(contenido)
        
        layout.addSpacing(20)
        
        # Botones
        botones_layout = QHBoxLayout()
        botones_layout.addStretch()
        
        btn_si = QPushButton('🚫 Sí, Quitar Todos')
        btn_si.setMinimumWidth(140)
        btn_si.setMinimumHeight(40)
        btn_si.setStyleSheet("""
            QPushButton {
                background-color: #f44336;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #da190b;
            }
            QPushButton:pressed {
                background-color: #ba0000;
            }
        """)
        
        btn_no = QPushButton('✗ Cancelar')
        btn_no.setMinimumWidth(120)
        btn_no.setMinimumHeight(40)
        btn_no.setStyleSheet("""
            QPushButton {
                background-color: #2196F3;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #0b7dda;
            }
            QPushButton:pressed {
                background-color: #0056b3;
            }
        """)
        
        botones_layout.addWidget(btn_si)
        botones_layout.addWidget(btn_no)
        botones_layout.addStretch()
        
        layout.addLayout(botones_layout)
        dialogo.setLayout(layout)
        
        # Conectar botones
        btn_si.clicked.connect(dialogo.accept)
        btn_no.clicked.connect(dialogo.reject)
        
        # Mostrar diálogo
        if dialogo.exec_() != QDialog.Accepted:
            self.mensaje('Ejecutado', 'Operación cancelada')
            return
        
        self.mostrarProceso.setText('Quitando todos los permisos...')
        QApplication.processEvents()
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            # Obtener todas las tablas del usuario
            tablas = self.permisos_usuario_actual.get('tablas', [])
            
            if not tablas:
                self.mensaje('Error', 'No hay tablas para actualizar')
                return
            
            # Revocar todos los permisos
            self.revocarTodosPermisosUsuario(host, bd, usuario_admin, contrasena, self.usuario_actual, tablas)
            
            self.mostrarProceso.setText(f'Todos los permisos han sido quitados a {self.usuario_actual}.')
            self.mensaje('Ejecutado', f'Permisos quitados para {self.usuario_actual}')
            
            # Actualizar lista
            self.validarPermisos()
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def revocarTodosPermisosUsuario(self, host, bd, usuario_admin, contrasena, usuario_objetivo, tablas):
        """Revoca todos los permisos del usuario en todas las tablas"""
        import psycopg2
        
        try:
            conn = psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario_admin, 
                password=contrasena, 
                port='5432'
            )
            cursor = conn.cursor()
            
            # Revocar permisos en todas las tablas
            for esquema, tabla, _, _, _, _ in tablas:
                try:
                    cursor.execute(f'REVOKE ALL ON TABLE "{esquema}"."{tabla}" FROM "{usuario_objetivo}";')
                except:
                    pass
            
            # Revocar conexión a la BD
            try:
                cursor.execute(f'REVOKE CONNECT ON DATABASE "{bd}" FROM "{usuario_objetivo}";')
            except:
                pass
            
            conn.commit()
            cursor.close()
            conn.close()
            
        except Exception as e:
            raise Exception(f"Error al revocar permisos: {str(e)}")
